dist: trusty
sudo: required
group: edge

env:
  - CXX="g++-6" CC="gcc-6"
# - CXX="g++-5" CC="gcc-5"
# - CXX="g++-4.9" CC="gcc-4.9"
# - CXX="clang++-3.7" CC="clang-3.7"

install:
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq $CC

script:
  - cmake -E make_directory build
  - cmake -E chdir build cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build build

deploy:
  skip_cleanup: true

after_success:
  - pushd build
  # Upload report to CodeCov
  - |
    if [ "$COVERAGE" == "lcov" ]; then
      bash <(curl -s https://codecov.io/bash); else echo "Codecov did not collect coverage reports"
    fi
