dist: trusty 
sudo: required
group: edge
language: python
python:
  - 3.6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

env:
- CC="gcc-6" PIC="OFF"
- CC="gcc-6" PIC="ON"

install:
  - sudo apt-get update -yqq
  - sudo apt-get --allow-unauthenticated install -yqq $CC

script:
  - gcc -v
  - cmake -E make_directory build
  - cmake -E chdir build cmake -DCMAKE_POSITION_INDEPENDENT_CODE=$PIC -DBUILD_SHARED_LIBS=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build build

deploy:
  skip_cleanup: true
