dist: trusty
sudo: required
group: edge
language: python
python:
  - 3.6

env:
- CC="gcc-4.8" SHARED="ON"
- CC="gcc-4.8" SHARED="OFF"

install:
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq $CC

script:
  - cmake -E make_directory build
  - cmake -E chdir build cmake -DBUILD_SHARED_LIBS=$SHARED -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build build

deploy:
  skip_cleanup: true
