dist: trusty
sudo: required
group: edge

env:
- CC="gcc-4.8" COVERAGE="lcov"

install:
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq $CC

script:
  - cmake -E make_directory build
  - cmake -E chdir build cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build build

deploy:
  skip_cleanup: true

after_success:
  - pushd build
  # Upload report to CodeCov
  - |
    if [ "$COVERAGE" == "lcov" ]; then
      bash <(curl -s https://codecov.io/bash); else echo "Codecov did not collect coverage reports"
    fi
